sensor:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} supply pressure"
    id: "${prefix}_supply_pressure"
    register_type: read
    address: 4023
    value_type: S_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    accuracy_decimals: 1
    filters:
      - multiply: .1
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} exhaust pressure"
    id: "${prefix}_exhaust_pressure"
    register_type: read
    address: 4024
    value_type: S_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    accuracy_decimals: 1
    filters:
      - multiply: .1
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} supply flow"
    id: "${prefix}_supply_flow"
    register_type: read
    address: 4032
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} supply fan"
    id: "${prefix}_supply_fan"
    register_type: read
    address: 4034
    value_type: U_WORD
    unit_of_measurement: "rpm"
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} supply temperature"
    id: "${prefix}_supply_temperature"
    register_type: read
    address: 4036
    value_type: S_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    filters:
      - multiply: .1
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} supply humidity"
    id: "${prefix}_supply_humidity"
    register_type: read
    address: 4037
    value_type: U_WORD
    unit_of_measurement: "%"
    entity_category: DIAGNOSTIC
    filters:
      - multiply: .1
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} exhaust flow"
    id: "${prefix}_exhaust_flow"
    register_type: read
    address: 4042
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} exhaust fan"
    id: "${prefix}_exhaust_fan"
    register_type: read
    address: 4044
    value_type: U_WORD
    unit_of_measurement: "rpm"
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} exhaust temperature"
    id: "${prefix}_exhaust_temperature"
    register_type: read
    address: 4046
    value_type: S_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    filters:
      - multiply: .1
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} exhaust humidity"
    id: "${prefix}_exhaust_humidity"
    register_type: read
    address: 4047
    value_type: U_WORD
    unit_of_measurement: "%"
    entity_category: DIAGNOSTIC
    filters:
      - multiply: .1

switch:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} imbalance allowed"
    id: "${prefix}_imbalance_allowed"
    register_type: holding
    address: 6033
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} on/off"
    id: "${prefix}_on_off"
    register_type: holding
    address: 8003
    inverted: true
    icon: "mdi:power-standby"

select:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} flow type"
    id: "${prefix}_flow_type"
    address: 6030
    value_type: U_WORD
    optionsmap:
      "Constant pulse width modulation": 1
      "Constant flow": 2
      "Constant mass flow": 3
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} bypass"
    id: "${prefix}_bypass"
    address: 6100
    value_type: U_WORD
    optionsmap:
      "auto": 0
      "closed": 1
      "open": 2
    entity_category: CONFIG

number:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} flow rate setting"
    id: "${prefix}_flow_rate_setting"
    address: 8002
    value_type: U_WORD
    min_value: 0
    max_value: 400
    step: 1
