sensor:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water temperature setting (duplicate)"
    id: "${prefix}_water_temperature_setting_duplicate"
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    device_class: TEMPERATURE
    entity_category: DIAGNOSTIC
    bitmask: 0xff
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} fan speed"
    id: "${prefix}_fan_speed"
    icon: "mdi:wind-power"
    register_type: holding
    address: 102
    unit_of_measurement: "r/min"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water inlet temperature"
    id: "${prefix}_water_inlet_temperature"
    register_type: holding
    address: 104
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-water"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} Water outlet temperature"
    id: "${prefix}_water_outlet_temperature"
    register_type: holding
    address: 105
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-water"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser temperature"
    id: "${prefix}_condenser_temperature"
    register_type: holding
    address: 106
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} ambient temperature"
    id: "${prefix}_ambient_temperature"
    register_type: holding
    address: 107
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser discharge temperature"
    id: "${prefix}_condenser_discharge_temperature"
    register_type: holding
    address: 108
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser suction temperature"
    id: "${prefix}_condenser_suction_temperature"
    register_type: holding
    address: 109
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant liquid side temperature"
    id: "${prefix}_refrigerant_liquid_temp"
    register_type: holding
    address: 112
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant gas side temperature"
    id: "${prefix}_refrigerant_gas_temp"
    register_type: holding
    address: 113
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} high pressure"
    id: "${prefix}_high_pressure"
    register_type: holding
    address: 116
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} low pressure"
    id: "${prefix}_low_pressure"
    register_type: holding
    address: 117
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating current"
    id: "${prefix}_operating_current"
    register_type: holding
    address: 118
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating voltage"
    id: "${prefix}_operating_voltage"
    register_type: holding
    address: 119
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: V
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating time"
    id: "${prefix}_operating_time"
    register_type: holding
    address: 122
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: DURATION
    unit_of_measurement: h
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} software version"
    id: "${prefix}_software_version"
    register_type: holding
    address: 130
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    skip_updates: 720
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} controller version"
    id: "${prefix}_controller_version"
    register_type: holding
    address: 131
    value_type: U_WORD
    skip_updates: 720
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus current"
    id: "${prefix}_dc_bus_current"
    register_type: holding
    address: 133
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus voltage"
    id: "${prefix}_dc_bus_voltage"
    register_type: holding
    address: 134
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: VOLTAGE
    unit_of_measurement: V
    filters:
      - multiply: .1
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} TF module temperature"
    id: "${prefix}_tf_module_temperature"
    register_type: holding
    address: 135
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water flow"
    id: "${prefix}_water_flow"
    register_type: holding
    address: 138
    unit_of_measurement: "m3/h"
    icon: "mdi:pump"
    value_type: U_WORD
    filters:
      - multiply: .01
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} power output"
    id: "${prefix}_power_output"
    register_type: holding
    address: 140
    device_class: POWER
    unit_of_measurement: "kW"
    value_type: U_WORD
    filters:
      - multiply: .01
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} temperature setting cooling upper limit"
    id: "${prefix}_temperature_setting_cooling_upper_limit"
    register_type: holding
    address: 201
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} temperature setting cooling lower limit"
    id: "${prefix}_temperature_setting_cooling_lower_limit"
    register_type: holding
    address: 202
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} temperature setting heating upper limit"
    id: "${prefix}_temperature_setting_heating_upper_limit"
    register_type: holding
    address: 203
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} temperature setting heating lower limit"
    id: "${prefix}_temperature_setting_heating_lower_limit"
    register_type: holding
    address: 204
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true

select:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} HVAC mode"
    id: "${prefix}_hvac_mode"
    icon: "mdi:heat-pump"
    address: 1
    value_type: U_WORD
    optionsmap:
      auto: 1
      cool: 2
      heat: 3

switch:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} on/off"
    id: "${prefix}_enable"
    icon: "mdi:power-standby"
    register_type: holding
    address: 0
    bitmask: 2
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} eco mode"
    id: "${prefix}_eco_mode"
    icon: "mdi:sprout"
    register_type: holding
    address: 5
    bitmask: 0x400
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} silent mode"
    id: "${prefix}_silent_mode"
    icon: "mdi:home-sound-out"
    register_type: holding
    address: 5
    bitmask: 0x40
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} climate curve active"
    id: "${prefix}_climate_curve_active"
    icon: "mdi:snowflake-thermometer"
    register_type: holding
    address: 5
    bitmask: 0x1000

number:
#  - platform: modbus_controller
#    modbus_controller_id: "${prefix}_modbus"
#    name: "${friendly_prefix} climate curve"
#    id: "${prefix}_climate_curve"
#    icon: "mdi:snowflake-thermometer"
#    address: 6
#    value_type: U_WORD
#    min_value: 1
#    max_value: 265
#    step: 1
#    lambda: "return int(x) & 0xff;"
#    write_lambda: |-
#      uint16_t modbus_value = int(x) | 0x100;
#      ESP_LOGD("main","sending modbus value: %d", modbus_value);
#      payload.push_back(modbus_value);
#      return x;
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water temperature setting"
    id: "${prefix}_water_temperature_setting"
    icon: "mdi:thermometer-water"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 11
    value_type: U_WORD
    min_value: 35
    max_value: 55
    step: 1
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} power limit"
    id: "${prefix}_power_limit"
    icon: "mdi:car-speed-limiter"
    address: 269
    value_type: U_WORD
    min_value: 0
    max_value: 8
    step: 1

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} fault"
    id: "${prefix}_fault"
    register_type: holding
    address: 124
    lambda: !lambda |-
      uint16_t int_mode = (data[item->offset] << 8) + data[item->offset+1];
      ESP_LOGD("main","Parsed operation mode int : %d", int_mode);
      std::string mode_str;
      switch (int_mode) {
        case 0:  mode_str = "None"; break;
        case 1:  mode_str = "Water flow fault (E8 displayed 3 times)"; break;
        case 2:  mode_str = "Phase loss or neutral wire and live wire are connected"; break;
        case 3:  mode_str = "Communication fault between controller and hydraulic"; break;
        case 4:  mode_str = "Final outlet water temperature sensor (T1) fault"; break;
        case 20: mode_str = "Low pressure protection"; break;
        case 21: mode_str = "High pressure protection"; break;
        case 23: mode_str = "Compressor overcurrent protection"; break;
        case 31: mode_str = "Anti-freeze mode protection"; break;
        default: mode_str = to_string(int_mode); break;
      }
      return mode_str;
