# Listing of entities that may not have accurate readings, are poorly
# documented, or have no clear purpose in general applications.

sensor:
  # Register address 103(PLC: 40104) PMV openness
  # Openness of the outdoor unit's electronic expansion valve in P
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} expansion valve openness"
    register_type: holding
    address: 103
    unit_of_measurement: "%"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  # Register address 106(PLC: 40107) T3 Temperature
  # Condenser temperature, unit: °C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser temperature"
    register_type: holding
    address: 106
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  # Register address 108(PLC: 40109) Discharge temperature
  # Compressor discharge temperature Tp unit: °C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser discharge temperature"
    register_type: holding
    address: 108
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  # Register address 109(PLC: 40110) Suction temperature
  # Compressor suction temperature Th, unit:°C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser suction temperature"
    register_type: holding
    address: 109
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  # Register address 112(PLC: 40113) T2
  # Refrigerant liquid side temperature, unit: °C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant liquid side temperature"
    register_type: holding
    address: 112
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  # Register address 113(PLC: 40114) T2B
  # Refrigerant gas side temperature, unit: °C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant gas side temperature"
    register_type: holding
    address: 113
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  # Register address 116(PLC: 40117) Pressure 1
  # Outdoor unit high pressure value, unit: kPa
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} high pressure"
    register_type: holding
    address: 116
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  # Register address 117(PLC: 40118) Pressure 2
  # Outdoor unit low pressure value, unit: kPa
  # Note: this reading appears to have always the same value
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} low pressure"
    register_type: holding
    address: 117
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  # 118 (PLC: 40119) Outdoor unit current
  # Outdoor unit operating current, unit: A
  # Note: the resolution of this reading is too low to be useful
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating current"
    id: "${prefix}_operating_current"
    register_type: holding
    address: 118
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  - platform: template
    name: "${friendly_prefix} apparent power"
    id: "${prefix}_apparent_power"
    lambda: "return id(${prefix}_operating_voltage).state * id(${prefix}_operating_current).state;"
    update_interval: 30s
    unit_of_measurement: VA
    device_class: APPARENT_POWER
    accuracy_decimals: 0
    entity_category: DIAGNOSTIC
  # 132(PLC: 40133) Unit target frequency
  # Hz
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} target frequency"
    register_type: holding
    address: 132
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: FREQUENCY
    unit_of_measurement: Hz
    disabled_by_default: true
  # 133(PLC: 40134)
  # DC bus current
  # Unit: A
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus current"
    register_type: holding
    address: 133
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  # 134(PLC: 40135)
  # DC bus voltage
  # The actual value/10, unit: V
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus voltage"
    register_type: holding
    address: 134
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: VOLTAGE
    unit_of_measurement: V
    disabled_by_default: true
  # Register address 135( PLC: 40136) TF module temperature
  # Feedback on outdoor unit, unit: °C
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} TF module temperature"
    register_type: holding
    address: 135
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true

number:
  # Register address 223(PLC: 40224) t_interval_C
  # Time interval of compressor start-up in cooling mode; range: 5~5 min,
  # default setting: 5 min
  # Note: this value does not accept any other setting than the default
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} cooling mode compressor startup interval"
    disabled_by_default: true
    device_class: DURATION
    unit_of_measurement: min
    entity_category: CONFIG
    address: 223
    value_type: U_WORD
    min_value: 5
    max_value: 6
    step: 1
    skip_updates: 30
  # Register address 224(PLC: 40225) dT1SC
  # Default setting: 5°C, range: 2~10°C, setting interval: 1°C
  # Note: this value does not accept any other setting than the default
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} cooling water temperature delta"
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: CONFIG
    address: 224
    value_type: U_WORD
    min_value: 2
    max_value: 10
    step: 1
    skip_updates: 30
  # Register address 228(PLC: 40229) t_interval_H
  # Time interval of compressor start-up in the heating mode; range: 5~5 min,
  # default setting: 5 min
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} heating mode compressor startup interval"
    disabled_by_default: true
    device_class: DURATION
    unit_of_measurement: min
    entity_category: CONFIG
    address: 228
    value_type: U_WORD
    min_value: 5
    max_value: 6
    step: 1
    skip_updates: 30
  # Register address 229(PLC: 40230) dT1SH
  # Default setting: 5°C, range: 2-20°C;
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} heating water temperature delta"
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: CONFIG
    address: 229
    value_type: U_WORD
    min_value: 2
    max_value: 10
    step: 1
    skip_updates: 30
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} power limit"
    icon: "mdi:car-speed-limiter"
    address: 269
    value_type: U_WORD
    min_value: 0
    max_value: 8
    step: 1
    entity_category: CONFIG
    disabled_by_default: true
    skip_updates: 30
