sensor:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water temperature setpoint (duplicate)"
    id: "${prefix}_water_temperature_setpoint_duplicate"
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    device_class: TEMPERATURE
    entity_category: DIAGNOSTIC
    bitmask: 0xff
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve selected"
    id: "${prefix}_climate_curve_selected"
    register_type: holding
    address: 6
    value_type: U_WORD
    entity_category: DIAGNOSTIC
    bitmask: 0xff
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} fan speed"
    id: "${prefix}_fan_speed"
    icon: "mdi:wind-power"
    register_type: holding
    address: 102
    unit_of_measurement: "r/min"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water inlet temperature"
    id: "${prefix}_water_inlet_temperature"
    register_type: holding
    address: 104
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-water"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} Water outlet temperature"
    id: "${prefix}_water_outlet_temperature"
    register_type: holding
    address: 105
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-water"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser temperature"
    id: "${prefix}_condenser_temperature"
    register_type: holding
    address: 106
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} ambient temperature"
    id: "${prefix}_ambient_temperature"
    register_type: holding
    address: 107
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: S_WORD
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser discharge temperature"
    id: "${prefix}_condenser_discharge_temperature"
    register_type: holding
    address: 108
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} condenser suction temperature"
    id: "${prefix}_condenser_suction_temperature"
    register_type: holding
    address: 109
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant liquid side temperature"
    id: "${prefix}_refrigerant_liquid_temp"
    register_type: holding
    address: 112
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} refrigerant gas side temperature"
    id: "${prefix}_refrigerant_gas_temp"
    register_type: holding
    address: 113
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} high pressure"
    id: "${prefix}_high_pressure"
    register_type: holding
    address: 116
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} low pressure"
    id: "${prefix}_low_pressure"
    register_type: holding
    address: 117
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: PRESSURE
    unit_of_measurement: kPa
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating current"
    id: "${prefix}_operating_current"
    register_type: holding
    address: 118
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating voltage"
    id: "${prefix}_operating_voltage"
    register_type: holding
    address: 119
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: VOLTAGE
    unit_of_measurement: V
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} operating time"
    id: "${prefix}_operating_time"
    register_type: holding
    address: 122
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: DURATION
    unit_of_measurement: h
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} software version"
    id: "${prefix}_software_version"
    register_type: holding
    address: 130
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    skip_updates: 720
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} controller version"
    id: "${prefix}_controller_version"
    register_type: holding
    address: 131
    value_type: U_WORD
    skip_updates: 720
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus current"
    id: "${prefix}_dc_bus_current"
    register_type: holding
    address: 133
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: CURRENT
    unit_of_measurement: A
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} DC bus voltage"
    id: "${prefix}_dc_bus_voltage"
    register_type: holding
    address: 134
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: VOLTAGE
    unit_of_measurement: V
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} TF module temperature"
    id: "${prefix}_tf_module_temperature"
    register_type: holding
    address: 135
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve calculated setpoint"
    id: "${prefix}_curve_calculated_setpoint"
    register_type: holding
    address: 136
    entity_category: DIAGNOSTIC
    value_type: U_WORD
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water flow"
    id: "${prefix}_water_flow"
    register_type: holding
    address: 138
    unit_of_measurement: "m3/h"
    icon: "mdi:pump"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: .01
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} output power"
    id: "${prefix}_power_output"
    register_type: holding
    address: 140
    device_class: POWER
    unit_of_measurement: W
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} cooling setpoint upper limit"
    id: "${prefix}_temperature_setting_cooling_upper_limit"
    register_type: holding
    address: 201
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} cooling setpoint lower limit"
    id: "${prefix}_temperature_setting_cooling_lower_limit"
    register_type: holding
    address: 202
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} heating setpoint upper limit"
    id: "${prefix}_temperature_setting_heating_upper_limit"
    register_type: holding
    address: 203
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} heating setpoint lower limit"
    id: "${prefix}_temperature_setting_heating_lower_limit"
    register_type: holding
    address: 204
    device_class: TEMPERATURE
    unit_of_measurement: "°C"
    value_type: U_WORD
    bitmask: 0xff
    entity_category: DIAGNOSTIC
    disabled_by_default: true


select:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} HVAC mode"
    id: "${prefix}_hvac_mode"
    icon: "mdi:heat-pump"
    address: 1
    value_type: U_WORD
    optionsmap:
      auto: 1
      cool: 2
      heat: 3
    entity_category: CONFIG

switch:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} on/off"
    id: "${prefix}_enable"
    icon: "mdi:power-standby"
    register_type: holding
    address: 0
    bitmask: 2
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} eco mode"
    id: "${prefix}_eco_mode"
    icon: "mdi:sprout"
    register_type: holding
    address: 5
    bitmask: 0x400
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} silent mode"
    id: "${prefix}_silent_mode"
    icon: "mdi:home-sound-out"
    register_type: holding
    address: 5
    bitmask: 0x40
    entity_category: CONFIG
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve mode"
    id: "${prefix}_curve_mode"
    icon: "mdi:snowflake-thermometer"
    register_type: holding
    address: 5
    bitmask: 0x1000
    entity_category: CONFIG

number:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} water temperature setpoint"
    id: "${prefix}_water_temperature_setpoint"
    icon: "mdi:thermometer-water"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 11
    value_type: U_WORD
    min_value: 25
    max_value: 55
    step: 1
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve heating setpoint1"
    id: "${prefix}_curve_heating_setpoint1"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 265
    value_type: U_WORD
    min_value: 25
    max_value: 65
    step: 1
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve heating setpoint2"
    id: "${prefix}_curve_heating_setpoint2"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 266
    value_type: U_WORD
    min_value: 25
    max_value: 65
    step: 1
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve heating ambient1"
    id: "${prefix}_curve_heating_ambient1"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 267
    value_type: S_WORD
    min_value: -25
    max_value: 35
    step: 1
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} curve heating ambient2"
    id: "${prefix}_curve_heating_ambient2"
    device_class: TEMPERATURE
    entity_category: CONFIG
    address: 268
    value_type: S_WORD
    min_value: -25
    max_value: 35
    step: 1
    disabled_by_default: true
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} power limit"
    id: "${prefix}_power_limit"
    icon: "mdi:car-speed-limiter"
    address: 269
    value_type: U_WORD
    min_value: 0
    max_value: 8
    step: 1
    entity_category: CONFIG
    disabled_by_default: true

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: "${prefix}_modbus"
    name: "${friendly_prefix} status"
    id: "${prefix}_status"
    register_type: holding
    address: 124
    entity_category: DIAGNOSTIC
    icon: mdi:alert
    lambda: !lambda |-
      uint16_t int_mode = (data[item->offset] << 8) + data[item->offset+1];
      ESP_LOGD("main","Found device status int : %d", int_mode);
      std::string mode_str;
      switch (int_mode) {
        case 0:  mode_str = "good"; break;
        case 1:  mode_str = "E0: Water flow fault (E8 displayed 3 times)"; break;
        case 2:  mode_str = "E1: Phase loss or neutral wire and live wire are connected"; break;
        case 3:  mode_str = "E2: Communication fault between controller and hydraulic"; break;
        case 4:  mode_str = "E3: Final outlet water temperature sensor (T1) fault"; break;
        case 5:  mode_str = "E4: Water tank temp. sensor (T5) fault"; break;
        case 6:  mode_str = "E5: The condensor outlet refrigerant temperature sensor (T3)"; break;
        case 7:  mode_str = "E6: The ambient temperature sensor (T4) fault"; break;
        case 8:  mode_str = "E7: Buffer tank up temperature sensor (Tbt1) fault"; break;
        case 9:  mode_str = "E8: Water flow failure"; break;
        case 10: mode_str = "E9: Compressor suction temp. sensor (Th) fault"; break;
        case 11: mode_str = "Ea: Compressor discharge temp. sensor (Tp) fault"; break;
        case 12: mode_str = "Eb: Solar temp. sensor (Tsolar) fault"; break;
        case 13: mode_str = "Ec: The balance tank low temp. sensor (Tbt2) fault"; break;
        case 14: mode_str = "Ed: The plate exchanger water inlet temp. sensor (Tw_in) fault"; break;
        case 15: mode_str = "Ee: The main control board of hydraulic module EEPROM"; break;
        case 20: mode_str = "P0: Low pressure protection"; break;
        case 21: mode_str = "P1: High pressure protection"; break;
        case 23: mode_str = "P3: Compressor overcurrent protection"; break;
        case 24: mode_str = "P4: compressor discharge temp. too high protection"; break;
        case 25: mode_str = "P5: high temperature difference protection between water inlet and water outlet of the plate heat exchanger"; break;
        case 26: mode_str = "P6: inverter module protection"; break;
        case 31: mode_str = "Pb: Anti-freeze mode protection"; break;
        case 33: mode_str = "Pd: high temperature protection of refrigerant outlet temp. of condenser"; break;
        case 38: mode_str = "Pp: water inlet temperature is higher than water outlet in heating mode"; break;
        case 39: mode_str = "H0: communication fault between main control board of hydraulic module and main control board PCB B"; break;
        case 40: mode_str = "H1"; break;
        case 41: mode_str = "H2"; break;
        case 42: mode_str = "H3"; break;
        case 43: mode_str = "H4"; break;
        case 44: mode_str = "H5"; break;
        case 45: mode_str = "H6: DC fan motor fault"; break;
        case 46: mode_str = "H7: main circuit voltage protection fault"; break;
        case 47: mode_str = "H8: pressure sensor fault"; break;
        case 48: mode_str = "H9"; break;
        case 49: mode_str = "Ha"; break;
        case 50: mode_str = "Hb"; break;
        case 52: mode_str = "Hd"; break;
        case 53: mode_str = "He"; break;
        case 54: mode_str = "Hf: inverter module board EE PROM fault"; break;
        case 55: mode_str = "Hh"; break;
        case 57: mode_str = "Hp"; break;
        case 65: mode_str = "C7"; break;
        case 112:mode_str = "bH"; break;
        case 116:mode_str = "F1"; break;
        case 134:mode_str = "L0: DC compressor inverter module fault"; break;
        case 135:mode_str = "L1: DC bus low voltage protection (from inverter module mostly when compressor running)"; break;
        case 136:mode_str = "L2: DC bus high voltage protection from DC driver"; break;
        case 138:mode_str = "L4: MCE fault"; break;
        case 139:mode_str = "L5: Zero speed protection"; break;
        case 141:mode_str = "L7: Phase sequence fault"; break;
        case 142:mode_str = "L8: Compressor frequency variation greater than 15Hz within one second protection"; break;
        case 143:mode_str = "L9: Actual compressor frequency differs from target frequency by more than 15Hz protection"; break;
        default: mode_str = to_string(int_mode); break;
      }
      return mode_str;
